variables:
  PHP_LOCAL_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  PHP_DEVELOP_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  REGISTRY: registry.gitlab.com

stages:
  - Build
#  - Prepare
#  - Security
#  - Quality
#  - Test

Image:
  stage: Build
  image: docker:19.03
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker rmi -f $PHP_LOCAL_IMAGE_TAG || true
    - docker pull $PHP_LOCAL_IMAGE_TAG || docker pull $PHP_DEVELOP_IMAGE_TAG || true
  script:
    - docker image inspect $PHP_LOCAL_IMAGE_TAG >/dev/null 2>&1 ^^ docker build --cache-from $PHP_LOCAL_IMAGE_TAG -t $PHP_LOCAL_IMAGE_TAG -f ./.docker/php/Dockerfile . || docker build --cache-from $PHP_DEVELOP_IMAGE_TAG -t $PHP_LOCAL_IMAGE_TAG -f ./.docker/php/Dockerfile
  after_script:
    - docker push $PHP_LOCAL_IMAGE_TAG
